### ISSUE TITLE
0.3.0 Java Support Endgame

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-azurefunctions#88]
## Features:
- [x] Can create Java function project #48 @jdneo
- [x] Can add Java function #49 @jdneo
- [x] Can deploy Java function project to cloud #50 @jdneo
- [x] Can local debug Java function through [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) @jdneo

## Bug fixes and improvements:
- [x] Java HttpTrigger fails to build #83 @jdneo

Please refer to https://github.com/Microsoft/vscode-azurefunctions/milestone/4 for details.

### On MacOS  @Eskibear 
- [x] Can create Java function project
- [x] Can add Java function
- [x] Can deploy Java function project to cloud
- [ ] Can local debug Java function through Java Extension Pack

### On Windows  @adashen 
- [x] Can create Java function project
- [x] Can add Java function
- [x] Can deploy Java function project to cloud
- [x] Can local debug Java function through Java Extension Pack

### On Linux  @bsaby 
- [x] Can create Java function project
- [x] Can add Java function
- [x] Can deploy Java function project to cloud
- [ ] Can local debug Java function through Java Extension Pack

**Comment by EricJizbaMSFT** [comment]
@jdneo Please make sure to have someone run these tests on all OS's (Mac, Linux, and Windows).

For Linux, we've been testing on Ubuntu 16.04, but it's not a big deal which one you choose.

**Comment by Eskibear** [comment]
On MacOS
- [ ] Can create Java function project
- [ ] Can add Java function
- [ ] Can deploy Java function project to cloud
- [ ] Can local debug Java function through Java Extension Pack 

https://github.com/Microsoft/vscode-azurefunctions/issues/102

**Comment by adashen** [comment]
On Windows 

 - [ ] Can create Java function project
 - [ ] Can add Java function
 - [ ] Can deploy Java function project to cloud
 - [ ] Can local debug Java function through Java Extension Pack

#106

**Comment by bsaby** [comment]
On Linux 

- [ ]  Can create Java function project
- [ ]  Can add Java function
- [ ]  Can deploy Java function project to cloud
- [ ]  Can local debug Java function through Java Extension Pack

#105

**Comment by jdneo** [comment]
Close this issue since 0.3.0 has been released.
